project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!kglab/"
    
website:
  title: "A Quick Course on Knowledge Graphs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01_intro.ipynb

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



